import{a as C,S as w,i as c}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const B="15433898-8e738b4ae400445fc36a380ef",R="https://pixabay.com/api/";async function m(r,t=1){const s={key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return(await C.get(R,{params:s})).data}let P=new w(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=document.querySelector(".gallery"),s=r.map(({webformatURL:a,largeImageURL:e,tags:o,likes:i,views:S,comments:L,downloads:x})=>`
        <li class="gallery-item">
          <div class="img-wrap">
            <a href="${e}" class="gallery-link">
              <img src="${a}" alt="${o}" class="gallery-image" />
            </a>
          </div>
          <div class="info">
            <div class="text-info"><span><b>Likes</b></span><span>${i}</span></div>
            <div class="text-info"><span><b>Views</b></span><span>${S}</span></div>
            <div class="text-info"><span><b>Comments</b></span><span>${L}</span></div>
            <div class="text-info"><span><b>Downloads</b></span><span>${x}</span></div>
          </div>
        </li>
      `).join("");t.insertAdjacentHTML("beforeend",s),P.refresh()}function q(){document.querySelector(".gallery").innerHTML=""}const A=document.querySelector(".btn-more"),y=document.querySelector(".loader");function b(){y.classList.add("active")}function f(){y.classList.remove("active")}function I(){A.classList.add("active")}function g(){A.classList.remove("active")}const l="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEaSURBVHgBrZZhDoIwDIUL0fjXo3gUb7R5Er0BHsXD7A+bASlhYeC6V4WXGCHr3reNtkAkqG2D9T70mh/HSj4HybyqyPQ9PeuaXlRQ19GFY4c5dDodLSHNK3/fSam29Q+0k7/N1ZAt5hCyh7kIKZl77y/IMBezgEwXTW4ienBxcc65DCQ0PDYCQghGMDASJJpzTG4ue0KABEHmKeBAQEPx3LiIhmKy/M+aitDyGJoPAWsI32vNWTXpVQnXRal2kPQmO7pPx6XpPRCQmsdjSZ8JhIA0FbOllMKsRZqCQoMpXCy0GJRrFc7hVpGLSVqFWaxk52ZnVgPbIaL5HhBovgVSMv+qg7kt9JznZ+VL//pL+5hWFXei+mwRj+UDSHQ9vnHBEYAAAAAASUVORK5CYII=",u=document.querySelector(".form"),M=document.querySelector(".btn-more");let d="",n=1;const v=15;let p=0;u.addEventListener("submit",async function(r){if(r.preventDefault(),d=u.elements["search-text"].value.trim(),!!d){n=1,q(),g(),b();try{const{hits:t,totalHits:s}=await m(d,n);if(f(),t.length===0){c.warning({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",iconUrl:l,maxWidth:432});return}p=s,h(t),I();const a=Math.ceil(p/v);n>=a&&(g(),c.info({message:"The end of search results.",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",iconUrl:l,maxWidth:432}))}catch{f(),c.error({message:"We are sorry, but you have reached the end of search results.",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",iconUrl:l,maxWidth:432})}}});M.addEventListener("click",async()=>{n+=1,b();try{const{hits:r}=await m(d,n);h(r);const t=Math.ceil(p/v);n>=t&&(g(),c.info({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",iconUrl:l,maxWidth:432})),f();const{height:s}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}catch{f(),c.error({message:"Error",messageColor:"#fff",messageSize:"16px",backgroundColor:"#ef4040",position:"topRight",iconUrl:l,maxWidth:432})}});
//# sourceMappingURL=index.js.map
